name: Update Version

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-version:
    name: "Update Version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update version
        run: |
          SYNAPSE_VERSION=$(curl --silent "https://api.github.com/repos/matrix-org/synapse/releases/latest" | jq -r .tag_name)

          git config --global user.name 'Joonas Myhrberg'
          git config --global user.email '9052157+myyra@users.noreply.github.com'

          sed -i "s/v[0-9]*\.[0-9]*.\.[0-9]*\.tar.gz/${SYNAPSE_VERSION}.tar.gz/" Dockerfile

          git add -A
          git diff-index --quiet HEAD || git commit -m "Update version"

          git tag $SYNAPSE_VERSION -m "version ${SYNAPSE_VERSION}" --force

          git push --follow-tags
